const medicamentos = [
    {
        "nome_generico": "Paracetamol",
        "nome_comercial": "Tylenol",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Paracetamol",
        "concentracao": "500mg",
        "fabricante": "Laboratório XYZ",
        "lote": "123456",
        "data_fabricacao": "2024-01-01",
        "data_validade": "2025-12-31",
        "indicacoes": "Dor de cabeça, febre",
        "posologia": "1 comprimido a cada 6 horas",
        "preco": 10.99,
        "data_compra": "2024-02-15",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Ibuprofeno",
        "nome_comercial": "Advil",
        "forma_farmaceutica": "Cápsula",
        "apresentacao": "Blister",
        "principio_ativo": "Ibuprofeno",
        "concentracao": "400mg",
        "fabricante": "Laboratório ABC",
        "lote": "789012",
        "data_fabricacao": "2023-06-01",
        "data_validade": "2024-12-01",
        "indicacoes": "Inflamação, dor muscular",
        "posologia": "1 cápsula a cada 8 horas",
        "preco": 12.50,
        "data_compra": "2023-07-20",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Amoxicilina",
        "nome_comercial": "Amoxil",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Amoxicilina",
        "concentracao": "500mg",
        "fabricante": "Laboratório DEF",
        "lote": "345678",
        "data_fabricacao": "2024-02-01",
        "data_validade": "2025-02-01",
        "indicacoes": "Infecções bacterianas",
        "posologia": "1 comprimido a cada 8 horas",
        "preco": 15.00,
        "data_compra": "2024-03-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Dipirona",
        "nome_comercial": "Novalgina",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Dipirona",
        "concentracao": "500mg",
        "fabricante": "Laboratório GHI",
        "lote": "456789",
        "data_fabricacao": "2023-08-01",
        "data_validade": "2024-08-01",
        "indicacoes": "Dor e febre",
        "posologia": "1 comprimido a cada 6 horas",
        "preco": 9.99,
        "data_compra": "2023-09-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Cefalexina",
        "nome_comercial": "Keflex",
        "forma_farmaceutica": "Cápsula",
        "apresentacao": "Blister",
        "principio_ativo": "Cefalexina",
        "concentracao": "500mg",
        "fabricante": "Laboratório JKL",
        "lote": "567890",
        "data_fabricacao": "2023-09-01",
        "data_validade": "2024-09-01",
        "indicacoes": "Infecções bacterianas",
        "posologia": "1 cápsula a cada 12 horas",
        "preco": 18.50,
        "data_compra": "2023-10-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Lorazepam",
        "nome_comercial": "Ativan",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Lorazepam",
        "concentracao": "2mg",
        "fabricante": "Laboratório MNO",
        "lote": "678901",
        "data_fabricacao": "2024-03-01",
        "data_validade": "2025-03-01",
        "indicacoes": "Ansiedade, insônia",
        "posologia": "1 comprimido à noite",
        "preco": 25.00,
        "data_compra": "2024-04-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Losartana",
        "nome_comercial": "Cozaar",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Losartana",
        "concentracao": "50mg",
        "fabricante": "Laboratório PQR",
        "lote": "789012",
        "data_fabricacao": "2024-04-01",
        "data_validade": "2025-04-01",
        "indicacoes": "Hipertensão arterial",
        "posologia": "1 comprimido ao dia",
        "preco": 22.00,
        "data_compra": "2024-05-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Omeprazol",
        "nome_comercial": "Prilosec",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Omeprazol",
        "concentracao": "20mg",
        "fabricante": "Laboratório STU",
        "lote": "890123",
        "data_fabricacao": "2024-05-01",
        "data_validade": "2025-05-01",
        "indicacoes": "Úlceras gástricas",
        "posologia": "1 comprimido ao dia",
        "preco": 17.00,
        "data_compra": "2024-06-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Simvastatina",
        "nome_comercial": "Zocor",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Simvastatina",
        "concentracao": "20mg",
        "fabricante": "Laboratório VWX",
        "lote": "901234",
        "data_fabricacao": "2024-06-01",
        "data_validade": "2025-06-01",
        "indicacoes": "Colesterol elevado",
        "posologia": "1 comprimido à noite",
        "preco": 30.00,
        "data_compra": "2024-07-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Metformina",
        "nome_comercial": "Glucophage",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Metformina",
        "concentracao": "500mg",
        "fabricante": "Laboratório YZA",
        "lote": "012345",
        "data_fabricacao": "2024-07-01",
        "data_validade": "2025-07-01",
        "indicacoes": "Diabetes tipo 2",
        "posologia": "1 comprimido duas vezes ao dia",
        "preco": 20.00,
        "data_compra": "2024-08-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Cetoconazol",
        "nome_comercial": "Nizoral",
        "forma_farmaceutica": "Creme",
        "apresentacao": "Tubo",
        "principio_ativo": "Cetoconazol",
        "concentracao": "2%",
        "fabricante": "Laboratório ABC",
        "lote": "123456",
        "data_fabricacao": "2024-08-01",
        "data_validade": "2025-08-01",
        "indicacoes": "Infecções fúngicas da pele",
        "posologia": "Aplicar na área afetada uma vez ao dia",
        "preco": 25.00,
        "data_compra": "2024-09-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Clonazepam",
        "nome_comercial": "Klonopin",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Clonazepam",
        "concentracao": "0.5mg",
        "fabricante": "Laboratório DEF",
        "lote": "234567",
        "data_fabricacao": "2024-09-01",
        "data_validade": "2025-09-01",
        "indicacoes": "Transtornos de ansiedade",
        "posologia": "1 comprimido à noite",
        "preco": 28.00,
        "data_compra": "2024-10-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Levotiroxina",
        "nome_comercial": "Synthroid",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Levotiroxina",
        "concentracao": "75mcg",
        "fabricante": "Laboratório GHI",
        "lote": "345678",
        "data_fabricacao": "2024-10-01",
        "data_validade": "2025-10-01",
        "indicacoes": "Hipotireoidismo",
        "posologia": "1 comprimido ao dia",
        "preco": 35.00,
        "data_compra": "2024-11-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Diazepam",
        "nome_comercial": "Valium",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Diazepam",
        "concentracao": "10mg",
        "fabricante": "Laboratório JKL",
        "lote": "456789",
        "data_fabricacao": "2024-11-01",
        "data_validade": "2025-11-01",
        "indicacoes": "Transtornos de ansiedade, espasmos musculares",
        "posologia": "1 comprimido a cada 8 horas",
        "preco": 32.00,
        "data_compra": "2024-12-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Naproxeno",
        "nome_comercial": "Naprosyn",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Naproxeno",
        "concentracao": "500mg",
        "fabricante": "Laboratório MNO",
        "lote": "567890",
        "data_fabricacao": "2024-12-01",
        "data_validade": "2025-12-01",
        "indicacoes": "Dor e inflamação",
        "posologia": "1 comprimido a cada 12 horas",
        "preco": 14.00,
        "data_compra": "2025-01-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Metronidazol",
        "nome_comercial": "Flagyl",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Metronidazol",
        "concentracao": "250mg",
        "fabricante": "Laboratório OPQ",
        "lote": "678901",
        "data_fabricacao": "2024-01-15",
        "data_validade": "2025-01-15",
        "indicacoes": "Infecções bacterianas e parasitárias",
        "posologia": "1 comprimido a cada 8 horas",
        "preco": 11.50,
        "data_compra": "2024-02-15",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Atorvastatina",
        "nome_comercial": "Lipitor",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Atorvastatina",
        "concentracao": "40mg",
        "fabricante": "Laboratório RST",
        "lote": "789012",
        "data_fabricacao": "2024-02-01",
        "data_validade": "2025-02-01",
        "indicacoes": "Colesterol elevado",
        "posologia": "1 comprimido à noite",
        "preco": 27.00,
        "data_compra": "2024-03-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Prednisona",
        "nome_comercial": "Deltasone",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Prednisona",
        "concentracao": "10mg",
        "fabricante": "Laboratório UVW",
        "lote": "890123",
        "data_fabricacao": "2024-03-01",
        "data_validade": "2025-03-01",
        "indicacoes": "Inflamação, doenças autoimunes",
        "posologia": "1 comprimido ao dia",
        "preco": 21.00,
        "data_compra": "2024-04-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Furosemida",
        "nome_comercial": "Lasix",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Furosemida",
        "concentracao": "40mg",
        "fabricante": "Laboratório XYZ",
        "lote": "901234",
        "data_fabricacao": "2024-04-01",
        "data_validade": "2025-04-01",
        "indicacoes": "Edema, hipertensão",
        "posologia": "1 comprimido ao dia",
        "preco": 19.00,
        "data_compra": "2024-05-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Doxorrubicina",
        "nome_comercial": "Adriamycin",
        "forma_farmaceutica": "Frasco",
        "apresentacao": "Frasco",
        "principio_ativo": "Doxorrubicina",
        "concentracao": "50mg",
        "fabricante": "Laboratório ABC",
        "lote": "012345",
        "data_fabricacao": "2024-05-01",
        "data_validade": "2025-05-01",
        "indicacoes": "Tratamento de câncer",
        "posologia": "Administrar conforme orientação médica",
        "preco": 150.00,
        "data_compra": "2024-06-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Ciproflaxacino",
        "nome_comercial": "Cipro",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Ciproflaxacino",
        "concentracao": "500mg",
        "fabricante": "Laboratório DEF",
        "lote": "123456",
        "data_fabricacao": "2024-06-01",
        "data_validade": "2025-06-01",
        "indicacoes": "Infecções bacterianas",
        "posologia": "1 comprimido a cada 12 horas",
        "preco": 23.00,
        "data_compra": "2024-07-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Cloridrato de Anlodipino",
        "nome_comercial": "Norvasc",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Anlodipino",
        "concentracao": "5mg",
        "fabricante": "Laboratório GHI",
        "lote": "234567",
        "data_fabricacao": "2024-07-01",
        "data_validade": "2025-07-01",
        "indicacoes": "Hipertensão arterial",
        "posologia": "1 comprimido ao dia",
        "preco": 28.00,
        "data_compra": "2024-08-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Tetraciclina",
        "nome_comercial": "Achromycin",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Tetraciclina",
        "concentracao": "250mg",
        "fabricante": "Laboratório JKL",
        "lote": "345678",
        "data_fabricacao": "2024-08-01",
        "data_validade": "2025-08-01",
        "indicacoes": "Infecções bacterianas",
        "posologia": "1 comprimido a cada 6 horas",
        "preco": 12.00,
        "data_compra": "2024-09-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Hydroxizina",
        "nome_comercial": "Atarax",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Hydroxizina",
        "concentracao": "25mg",
        "fabricante": "Laboratório MNO",
        "lote": "456789",
        "data_fabricacao": "2024-09-01",
        "data_validade": "2025-09-01",
        "indicacoes": "Ansiedade, alergias",
        "posologia": "1 comprimido a cada 6 horas",
        "preco": 15.00,
        "data_compra": "2024-10-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Gabapentina",
        "nome_comercial": "Neurontin",
        "forma_farmaceutica": "Cápsula",
        "apresentacao": "Blister",
        "principio_ativo": "Gabapentina",
        "concentracao": "300mg",
        "fabricante": "Laboratório OPQ",
        "lote": "567890",
        "data_fabricacao": "2024-10-01",
        "data_validade": "2025-10-01",
        "indicacoes": "Dor neuropática, epilepsia",
        "posologia": "1 cápsula a cada 8 horas",
        "preco": 40.00,
        "data_compra": "2024-11-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Miconazol",
        "nome_comercial": "Monistat",
        "forma_farmaceutica": "Creme",
        "apresentacao": "Tubo",
        "principio_ativo": "Miconazol",
        "concentracao": "2%",
        "fabricante": "Laboratório RST",
        "lote": "678901",
        "data_fabricacao": "2024-11-01",
        "data_validade": "2025-11-01",
        "indicacoes": "Infecções fúngicas",
        "posologia": "Aplicar na área afetada duas vezes ao dia",
        "preco": 22.00,
        "data_compra": "2024-12-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Sulfametoxazol + Trimethoprim",
        "nome_comercial": "Bactrim",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Sulfametoxazol + Trimethoprim",
        "concentracao": "800mg + 160mg",
        "fabricante": "Laboratório UVW",
        "lote": "789012",
        "data_fabricacao": "2024-12-01",
        "data_validade": "2025-12-01",
        "indicacoes": "Infecções bacterianas",
        "posologia": "1 comprimido a cada 12 horas",
        "preco": 27.00,
        "data_compra": "2025-01-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Cloridrato de Amitriptilina",
        "nome_comercial": "Elavil",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Amitriptilina",
        "concentracao": "25mg",
        "fabricante": "Laboratório XYZ",
        "lote": "890123",
        "data_fabricacao": "2024-01-01",
        "data_validade": "2025-01-01",
        "indicacoes": "Depressão, ansiedade",
        "posologia": "1 comprimido à noite",
        "preco": 18.00,
        "data_compra": "2024-02-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Ranitidina",
        "nome_comercial": "Zantac",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Ranitidina",
        "concentracao": "150mg",
        "fabricante": "Laboratório ABC",
        "lote": "901234",
        "data_fabricacao": "2024-02-01",
        "data_validade": "2025-02-01",
        "indicacoes": "Úlceras gástricas, refluxo ácido",
        "posologia": "1 comprimido duas vezes ao dia",
        "preco": 12.00,
        "data_compra": "2024-03-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Sildenafil",
        "nome_comercial": "Viagra",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Sildenafil",
        "concentracao": "50mg",
        "fabricante": "Laboratório DEF",
        "lote": "012345",
        "data_fabricacao": "2024-03-01",
        "data_validade": "2025-03-01",
        "indicacoes": "Disfunção erétil",
        "posologia": "1 comprimido 1 hora antes da relação sexual",
        "preco": 45.00,
        "data_compra": "2024-04-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Loratadina",
        "nome_comercial": "Claritin",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Loratadina",
        "concentracao": "10mg",
        "fabricante": "Laboratório GHI",
        "lote": "123456",
        "data_fabricacao": "2024-04-01",
        "data_validade": "2025-04-01",
        "indicacoes": "Alergias",
        "posologia": "1 comprimido ao dia",
        "preco": 13.00,
        "data_compra": "2024-05-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    },
    {
        "nome_generico": "Azitromicina",
        "nome_comercial": "Zithromax",
        "forma_farmaceutica": "Comprimido",
        "apresentacao": "Blister",
        "principio_ativo": "Azitromicina",
        "concentracao": "500mg",
        "fabricante": "Laboratório JKL",
        "lote": "234567",
        "data_fabricacao": "2024-05-01",
        "data_validade": "2025-05-01",
        "indicacoes": "Infecções bacterianas",
        "posologia": "1 comprimido a cada 24 horas",
        "preco": 29.00,
        "data_compra": "2024-06-01",
        "imagem": "https://febrafar.com.br/wp-content/webp-express/webp-images/uploads/2023/11/Mockup-3D-GENERICO-2-1536x1024.png.webp"
    }
];